platform :ios, '11.0'

use_frameworks!

target 'XDHelper_Example' do
  pod 'XDHelper', :path => '../'

  pod 'SwifterSwift', '~> 5.2.0'
  
  target 'XDHelper_Tests' do
    inherit! :search_paths

    
  end
end
